<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model"
    nsURI="http://eclipse.org/mylyn/models/epub" nsPrefix="model">
  <eSubpackages name="dc" nsURI="http://purl.org/dc/elements/1.1/" nsPrefix="dc">
    <eClassifiers xsi:type="ecore:EClass" name="Language" instanceTypeName="language"/>
    <eClassifiers xsi:type="ecore:EClass" name="Title" instanceTypeName="title"/>
    <eClassifiers xsi:type="ecore:EClass" name="Identifier" instanceTypeName="identifier">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="BookId"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="scheme" eType="#//opf/scheme"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="creator">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="role" eType="#//opf/role"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="subject"/>
    <eClassifiers xsi:type="ecore:EClass" name="description"/>
    <eClassifiers xsi:type="ecore:EClass" name="rights"/>
    <eClassifiers xsi:type="ecore:EClass" name="publisher"/>
    <eClassifiers xsi:type="ecore:EClass" name="contributor"/>
    <eClassifiers xsi:type="ecore:EClass" name="date">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="event" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="type"/>
    <eClassifiers xsi:type="ecore:EClass" name="format"/>
    <eClassifiers xsi:type="ecore:EClass" name="source"/>
    <eClassifiers xsi:type="ecore:EClass" name="relation"/>
    <eClassifiers xsi:type="ecore:EClass" name="coverage"/>
  </eSubpackages>
  <eSubpackages name="opf" nsURI="http://www.idpf.org/2007/opf" nsPrefix="opf">
    <eClassifiers xsi:type="ecore:EClass" name="package">
      <eStructuralFeatures xsi:type="ecore:EReference" name="manifest" lowerBound="1"
          eType="#//opf/Manifest" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="metadata" eType="#//opf/Metadata"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="spine" lowerBound="1"
          eType="#//opf/spine" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="guide" eType="#//opf/guide"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="2.0" unsettable="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="unique_identifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Metadata" instanceTypeName="metadata">
      <eStructuralFeatures xsi:type="ecore:EReference" name="titles" lowerBound="1"
          upperBound="-1" eType="#//dc/Title" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="creators" lowerBound="1"
          upperBound="-1" eType="#//dc/creator" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subjects" upperBound="-1"
          eType="#//dc/subject" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="descriptions" eType="#//dc/description"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="publisher" eType="#//dc/publisher"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="contributors" eType="#//dc/contributor"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dates" eType="#//dc/date"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="types" eType="#//dc/type"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="metadata" eType="#//opf/Metadata"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="formats" eType="#//dc/format"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="identifiers" lowerBound="1"
          upperBound="-1" eType="#//dc/Identifier" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="sources" eType="#//dc/source"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="languages" lowerBound="1"
          upperBound="-1" eType="#//dc/Language" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="relations" eType="#//dc/relation"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="coverages" eType="#//dc/coverage"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="rights" eType="#//dc/rights"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Manifest" instanceTypeName="manifest">
      <eStructuralFeatures xsi:type="ecore:EReference" name="items" lowerBound="1"
          upperBound="-1" eType="#//opf/item" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="item">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="href" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="media_type" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fallback" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fallback_style" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="required_namespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="required_modules" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="Manifest" lowerBound="1"
          eType="#//opf/Manifest" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="spine">
      <eStructuralFeatures xsi:type="ecore:EReference" name="spineItems" upperBound="-1"
          eType="#//opf/itemref" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="scheme" instanceTypeName="scheme"/>
    <eClassifiers xsi:type="ecore:EDataType" name="role" instanceTypeName="role"/>
    <eClassifiers xsi:type="ecore:EClass" name="guide">
      <eStructuralFeatures xsi:type="ecore:EReference" name="guideItems" upperBound="-1"
          eType="#//opf/reference" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="reference">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="href" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="itemref">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="idref" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="linear" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
